// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    return $.ajax({
      url: 'http://localhost:80',
      method: 'get',
      jsonpCallback: 'callback',
      dataType: 'jsonp',
      success: function(data) {
        return Morris.Bar({
          element: 'chart',
          data: data,
          xkey: 'title',
          ykeys: ['value'],
          labels: ['Cities'],
          barColors: ['black'],
          gridTextColor: ['black'],
          gridTextSize: 15
        });
      }
    });
  });

}).call(this);
